dasch-swiss/dsp-js-lib

- .gitignore
- README.md
- package-lock.json
- package.json
- tsconfig.json
As discussed, I separated build files from source code. All build files go into a `build` folder, tarball packages go into a `dist` folder.
Further details cited from the ReadMe update in this commit:
> This package provides the following short-hand scripts:
> 
> 1. `npm run test`: Runs the project's tests defined in `./karma.conf.js`. The coverage data is saved into the `./coverage/` folder.
> 2. `npm run build`: Builds the whole project without testing and puts the files into the `./build/` folder.
> 3. `npm run yalc-publish`: Executes 2 and publishes the package to the yalc app store.
> 4. `npm run npm-pack`: Executes 1, 2 and packs the `./build/` folder into an NPM tgz package. The package is moved into a `./dist/` folder.
> 5. `npm run npm-publish`: Executes 4 and publishes the …
> Separated build files from source code, improved scripts

- src/api/admin/groups/groups-endpoint.spec.ts
- src/api/admin/permissions/permissions-endpoint.spec.ts
- src/api/admin/projects/projects-endpoint.spec.ts
- src/api/admin/users/users-endpoint.spec.ts
- src/api/v2/authentication/authentication-endpoint.spec.ts
- src/api/v2/list/lists-endpoint.ts
- src/api/v2/ontology/ontologies-endpoint.ts
- src/api/v2/resource/resources-endpoint.spec.ts
- src/api/v2/resource/resources-endpoint.ts
- src/api/v2/search/search-endpoint.spec.ts
- src/api/v2/search/search-endpoint.ts
- src/api/v2/v2-endpoint.ts
- src/cache/ListNodeCache.spec.ts
- src/cache/ListNodeCache.ts
- src/cache/OntologyCache.spec.ts
- src/cache/OntologyCache.ts
- src/cache/UserCache.spec.ts
- src/cache/UserCache.ts
- src/index.ts
- src/knora-api-connection.ts
- src/models/v2/resources/ResourcesConversionUtil.spec.ts
- src/models/v2/resources/ResourcesConversionUtil.ts
Caches are instantiated in the v2 endpoint at construction time so the client does not have to do instantiate caches.
closes #78
> Instantiate ontology cache in v2 endpoint

- package-lock.json
- package.json
- test-framework/yalc.lock
This PR changes the version of `rxjs` and `typescript` so that they are compatible with Angular 8.
closes #148
> Adapt version of rxjs and typescript

- test-framework/e2e/src/app.e2e-spec.ts
This PR changes the assertions in the E2E tests so that search tests do not expect an exact number of results (see https://github.com/dasch-swiss/knora-api/pull/1615#issuecomment-610252259). The data can always change in knora-api, but this is irrelevant to these tests. They just have to make sure that the result can be obtained and deserialized correctly.
> Test Framework: Do Not Check for Exact Number of Search Results in E2E Tests

- .gitignore
- package.json
- src/index.ts
- src/models/v2/resources/values/create/create-interval-value.ts
- test-framework/yalc.lock
Fixes an issue caused by a missing decorator.
> Add missing decorator

- Makefile
- README.md
- package-lock.json
- package.json
- rxjs.md
- test-framework/Dockerfile
- test-framework/package.json
- test-framework/src/app/app.component.ts
- test-framework/yalc.lock
This PR makes RxJS a peer dependency of the lib. This is necessary because the lib exposes RxJS's `Observable` in its public API. The lib is used by an Angular application that also requires RxJS. If the two versions are different, then the two Observables are treated as if they were different classes, resulting in a compile error like
> Types of property 'source' are incompatible.
Type 'import(".../knora-api-js-lib/test-framework/node_modules/@knora/api/node_modules/rxjs/internal/Observable").Observable<any>' is not assignable to type 'import(".../test-framework/node_modules/rxjs/internal/Observable").Observable<any>'.
I think this is exactly what peer dependencies attempt to solve:
> But now what if JacksModule exposes its dependency on JillsModule in some way. It accepts an instance of …
> Make RxJS a Peer Dep

- Makefile
- package-lock.json
- package.json
- test-framework/src/app/app.component.ts
- test/data/api/v2/mock-resource.ts
This PR prepares the automated publication process of the dev package.
The lib contains mock factories to generate test data that are not exported for the productive build. By adding those files to the build of the dev packag, these can be used by knora-ui-ng-lib.
In a subsequent PR, I will try to add a script to automate the build of the dev package.
> Integrate mockresource

- Makefile
- use a tagged version of Knora in tests on github-ci
- make curl retry after failed requests
> Use tagged Knora version

- Makefile
- design-documentation.md
- src/cache/OntologyCache.spec.ts
- src/cache/OntologyCache.ts
- src/models/v2/resources/ResourcesConversionUtil.spec.ts
- test/data/api/v2/mock-ontology-assertions.ts
- test/data/api/v2/mockOntology.ts
resolves https://dasch.myjetbrains.com/youtrack/issue/DSP-175
additional improvements will be done in https://dasch.myjetbrains.com/youtrack/issue/DSP-237
> Ontology Cache: Ignore third-party properties consistently

- src/models/v2/ontologies/OntologyConversionUtil.spec.ts
- src/models/v2/ontologies/OntologyConversionUtil.ts
follow knora's recipe for forging an IRI: https://github.com/dasch-swiss/knora-api/blob/0127dcae27e46bc3a4c9947282c30038c0a25d20/webapi/src/main/scala/org/knora/webapi/Settings.scala#L54
> ontology IRI: ignore port if not running on localhost

- .github/workflows/main.yml
- README.md
- package-lock.json
- package.json
I created two "test" releases on Github to see if the expected publish process will run. I have already deleted these releases. But you can still have a look at the workflow: https://github.com/dasch-swiss/knora-api-js-lib/runs/780497476?check_suite_focus=true
In this PR I removed the `--dry-run` flag from `npm publish` and updated the version number to next prerelease `v1.0.0-rc.3`. When this PR is merged, we can create new release on Github and the CI workflow will publish a new package to npm.
> Preparation for next pre-release 1.0.0-rc.3

- .github/workflows/main.yml
This PR splits the Gren workflow step into two variations: one runs on prerelease with the `--prerelease` option and one on release without this parameter.
The options parameter is a new feature of the latest release of [lakto/gren-action](https://github.com/lakto/gren-action/tree/v2.0.0)
> Update process of release notes

- src/models/v2/custom-converters/has-cardinality-for-property-converter.ts
resolves DSP-1138
For the reviewers. You can have a look in the updated file in `deserialize` that there we have `guiOrder` definition but it was missing in `serialize`
> DSP-1138 Add missing guiOrder to serialize IHasProperty

- src/api/endpoint.ts
- src/api/operators/retryOnError.spec.ts
- src/api/operators/retryOnError.ts
resolves DSP-170
This PR introduces a custom RxJS operator called `retryOnError` (inspired by https://medium.com/angular-in-depth/retry-failed-http-requests-in-angular-f5959d486294).
The operator retries failed HTTP request for specified error status codes. If the error is the user's fault (malformed query etc.), no retry should be performed. Retries should happen when the network is unstable ([XMLHttpRequest](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest) [status 0](https://stackoverflow.com/questions/47424413/rxjs-5-how-to-get-statuscode-on-catch)):
> feat(endpoint): Retry failed HTTP requests (DSP-170)

- src/api/endpoint.spec.ts
- src/api/endpoint.ts
> fix(endpoint)!: resolve set-cookie issue (DSP-1827)

- src/api/v2/search/search-endpoint-v2.ts
- src/models/v2/resources/ResourcesConversionUtil.ts
- src/models/v2/resources/read/read-resource-sequence.ts
> fix: fix gravsearch results infinite loading (DEV-1541)

- src/api/endpoint.ts
- src/knora-api-config.spec.ts
- src/knora-api-config.ts
- test-framework/src/app/app.component.ts
> chore!: remove zio endpoint implementation

- scripts/v2-test-data-config.json
- src/api/v2/ontology/ontologies-endpoint.spec.ts
- test/data/api/v2/mock-ontology.ts
> test: Remove tests depending on removed test data

- package-lock.json
- src/api/v2/resource/resources-endpoint-v2.ts
- src/api/v2/values/values-endpoint-v2.ts
- src/api/v2/values/values-endpoint.spec.ts
This represents a breaking change in the sense that when using the dsp-js-lib the asset upload must be done using dsp-ingest and cannot be done using Sipi anymore.
> feat!: Send X-Asset-Ingested header for update/create of value and resources (DEV-2628)

- package.json
- src/models/v2/Constants.ts
- src/models/v2/resources/values/create/create-file-value.ts
- src/models/v2/resources/values/update/update-file-value.ts
- vars.mk
> refactor: use stillimagefilevaluehasexternalurl (DEV-4109)
