src/models/v2/resources/ResourcesConversionUtil.spec.ts, src/models/v2/resources/ResourcesConversionUtil.ts, src/models/v2/resources/read-resource.ts
=> Simplify Access of Values of a ReadResource

src/models/v2/Constants.ts, src/models/v2/custom-converters/date-time-stamp-converter.ts, src/models/v2/ontologies/read-ontology.ts, src/models/v2/resources/ResourcesConversionUtil.spec.ts, src/models/v2/resources/read-resource.ts, src/models/v2/resources/values/read-value.ts
Adds missing properties to `ReadResource` and `ReadValue`.
closes #34
=> feature (resource and value): add missing properties

src/api/endpoint.spec.ts, src/api/endpoint.ts, src/api/v2/search/search-endpoint.spec.ts, src/api/v2/search/search-endpoint.ts, src/api/v2/v2-endpoint.ts, src/models/v2/Constants.ts, src/models/v2/resources/ResourcesConversionUtil.ts, src/models/v2/search/count-query-response.ts, test/data/api/v2/search/count-query-result.json
This PR adds the v2 search endpoint.
=> Search endpoint

src/models/v2/resources/values/read-date-value.ts, src/models/v2/resources/values/read-geom-value.ts, src/models/v2/resources/values/read-value.ts
This PR adds missing properties to ReadValue's constructor.
=> ReadValue: add missing properties to constructor

src/api/v2/authentication/authentication-endpoint.spec.ts, src/api/v2/authentication/authentication-endpoint.ts
=> Add login by email and iri

src/cache/OntologyCache.ts, src/index.ts
=> Export missing members

src/api/v2/authentication/authentication-endpoint.spec.ts, src/api/v2/authentication/authentication-endpoint.ts, src/index.ts, src/models/v2/authentication/credentials-reponse.ts, src/models/v2/authentication/credentials-response.ts
=> Add method to check credentials

src/models/admin/update-project-request.ts
Fixes #100.
Needs https://github.com/dasch-swiss/knora-api/pull/1519.
=> fix(admin): Make all properties in UpdateProjectRequest optional

scripts/v2-test-data-config.json, src/api/v2/values/values-endpoint.spec.ts, src/models/v2/resources/values/create/create-file-value.ts, src/models/v2/resources/values/read/read-file-value.ts, src/models/v2/resources/values/update/update-file-value.ts
This PR fixes inheritance issues in the file value classes.
=> fix file value classes

src/index.ts, src/models/v2/Constants.ts
=> Add missing constants for file values

src/api/admin/lists/lists-endpoint.spec.ts, src/api/admin/lists/lists-endpoint.ts
related to https://github.com/dasch-swiss/knora-api/pull/1560
=> Admin List: fix wrong HTTP method

Makefile
relates to https://github.com/dasch-swiss/knora-api/issues/1554
=> Automate client code integration

src/api/v2/ontology/ontologies-endpoint.spec.ts, src/models/api-response-error.ts, src/models/v2/ontologies/read-ontology.ts
=> Add label to ReadOntology

src/api/admin/users/users-endpoint.spec.ts, src/api/admin/users/users-endpoint.ts
needs https://github.com/dasch-swiss/knora-api/pull/1583
closes #137
=> test (admin): adapt test for updateUserSystemAdminMembership

package-lock.json, test-framework/e2e/src/app.e2e-spec.ts
This PR adapts assertions since Knora test data has changed.
=> tests (it): adapt assertions

src/index.ts
=> fix (index.ts): add time values to public api

src/models/v2/resources/read/read-resource.ts
This PR fixes an import from `index.ts` that resulted in a circular dep.
=> Fix import from index.ts

src/index.ts
=> fix (index.ts): export PropertyDefinition

src/models/v2/resources/read/read-resource.ts
fixes a problem with a method's return type, see https://github.com/dasch-swiss/knora-ui-ng-lib/pull/27#discussion_r393819787
=> Fix return type of link prop method

src/api/endpoint.ts
This PR fixes an import from RxJS.
closes #146
=> Fix Import from RxJS

src/index.ts, test-framework/src/app/app.component.ts
This PR adds missing exports to index.ts.
=> Add Missing Exports to Index.ts

.github/workflows/main.yml
This PR fixes a space issue when building the test app in Docker.
=> Docker Free Disk

src/api/admin/admin-endpoint.ts, src/api/admin/groups/groups-endpoint-admin.ts, src/api/admin/lists/lists-endpoint-admin.ts, src/api/admin/permissions/permissions-endpoint-admin.ts, src/api/admin/projects/projects-endpoint-admin.ts, src/api/admin/users/users-endpoint-admin.ts, src/api/v2/authentication/authentication-endpoint-v2.ts, src/api/v2/list/lists-endpoint-v2.ts, src/api/v2/ontology/ontologies-endpoint-v2.ts, src/api/v2/resource/resources-endpoint-v2.ts, src/api/v2/search/search-endpoint-v2.ts, src/api/v2/search/search-endpoint.spec.ts, src/api/v2/v2-endpoint.ts, src/api/v2/values/values-endpoint-v2.ts, src/index.ts
https://dasch.myjetbrains.com/youtrack/issue/DSP-182
=> Add missing exports

Makefile, README.md, package.json, scripts/mock-exports.json, scripts/prepare-dev-publication.js
This PR introduces a script that prepares a dev package for publication:
- add files from "test" in `package.json`
- add exports for mocks in `index.ts`
- do not exclude "test" folder in `tsconfig`
=> Prepare Dev Package

README.md
resolves https://dasch.myjetbrains.com/youtrack/issue/DSP-273
=> Explain how to build a local dev version

CHANGELOG.md, Makefile, package-lock.json, package.json
=> Wip/prepare rc.1

src/api/endpoint.spec.ts, src/api/v2/resource/resources-endpoint.spec.ts, src/api/v2/search/search-endpoint.spec.ts, src/models/api-response-error.ts, test-framework/src/app/app.component.ts, test/mockajaxcall.ts
resolves https://dasch.myjetbrains.com/youtrack/issue/DSP-345
=> Fix bug ApiResonseError

.github/workflows/main.yml, .gitignore, README.md
This PR resolves:
* issue in README (Title and NPM badge)
* Publish to npm as prerelease (with `--tag rc`) or as release
* Ignore vscode settings in git
=> Readme and workflow fix

scripts/mock-exports.json, test-framework/src/app/app.component.ts, test-framework/yalc.lock, test/data/api/admin/mockUsers.ts
@kilchenmann You can now use `MockUsers` to mock one or multiple users.
See https://github.com/dasch-swiss/knora-api-js-lib/blob/f00d42b44da75b59c3e300d2d1c2babaed57eb9f/test-framework/src/app/app.component.ts#L69-L70
=> Mock users

src/api/v2/resource/resources-endpoint-v2.ts, src/api/v2/resource/resources-endpoint.spec.ts, src/models/v2/resources/ResourcesConversionUtil.spec.ts, src/models/v2/resources/delete/delete-resource.ts, src/models/v2/resources/read/read-resource.ts, src/models/v2/resources/update/update-resource-metadata.ts
Resolves [DSP-438](https://dasch.myjetbrains.com/youtrack/issue/DSP-438)
=> fix: Replace DateDate by Date

.github/workflows/main.yml, Makefile
Resolves [DSP-435](https://dasch.myjetbrains.com/youtrack/issue/DSP-435)
=> Github CI: Workflow splited into single steps

src/api/v2/search/search-endpoint-v2.ts, src/index.ts, src/interfaces/models/v2/i-fulltext-search-params.ts, src/interfaces/models/v2/i-label-search-params.ts
resolves [DSP-531](https://dasch.myjetbrains.com/youtrack/issue/DSP-531)
resolves [DSP-532](https://dasch.myjetbrains.com/youtrack/issue/DSP-532)
=> Export IPermissions, IFulltextSearchParams, ILabelSearchParams interfaces

src/index.ts
Export BaseValue for use in DSP-UI
=> Export BaseValue

test/data/api/v2/mock-ontology.ts
https://dasch.myjetbrains.com/youtrack/issue/DSP-553
=> Mock minimal ontology

CHANGELOG.md, Makefile, package-lock.json, package.json
=> Update knora api version to rc.12

CHANGELOG.md, package-lock.json, package.json
=> Prerelease: 1.0.0-rc.10

CHANGELOG.md, package-lock.json, package.json
=> Prerelease v1.0.0-rc.12

tsconfig.json
https://github.com/dasch-swiss/dsp-js-lib/pull/235 accidentally brought this change to master
=> Revert change for tsconfig

.github/pull_request_template.md
resolves [DSP-702](https://dasch.myjetbrains.com/youtrack/issue/DSP-702)
=> DSP-702 Add template for PRs

package-lock.json
Resolves [Security alert for node-forge](https://github.com/dasch-swiss/dsp-js-lib/network/alert/package-lock.json/node-forge/closed)
=> Security update for node-forge

README.md
This PR adds missing documentation to the `README` about how to integrate generated test data.
=> Explain integration with knora-api

src/api/v2/ontology/ontologies-endpoint-v2.ts, src/api/v2/ontology/ontologies-endpoint.spec.ts, src/models/v2/ontologies/OntologyConversionUtil.ts, src/models/v2/ontologies/ontology-metadata.ts
resolves [DSP-863](https://dasch.myjetbrains.com/youtrack/issue/DSP-863)
=> Handle Empty Response when Requesting Ontologies for a Project

Makefile, README.md, package.json, scripts/integrate-files-system.js, src/api/system/health/health-endpoint.spec.ts, test/data/api/system/health/get-health-response.json, test/data/api/system/health/maintenance-mode-response.json, test/data/api/system/health/response-headers.txt, test/data/api/system/health/running-response.json, test/data/api/system/health/stopped-response.json
=> DSP-817 Health Endpoint: integrate test data

.github/workflows/main.yml, CHANGELOG.md
resolves DSP-920 
Update CHANGELOG
=> DSP-920 Renaming default github branch to "main"

vars.mk
Fixes error when getting test data.
=> Rename knora-api repo

.gitignore, test/data/api/v2/mock-resource.ts
=> DSP-1035 - MockResource Rename Methods

.github/workflows/main.yml, CHANGELOG.md
Fix the release issue with release-please-action. Found the solution here:
https://github.com/google-github-actions/release-please-action/issues/78#issuecomment-708836986
=> chore: Release 1.0.1

.github/workflows/main.yml, CHANGELOG.md, package-lock.json, package.json
I forgot to update version number
=> Release v1.0.1

src/api/endpoint.spec.ts, src/api/endpoint.ts, src/api/v2/search/search-endpoint.spec.ts
resolves DSP-1179
HTTP methods can receive additional header options.
=> Pass additional header options

.github/workflows/main.yml
=> chore(CI): Bring back release-please-action

src/models/v2/Constants.ts
resolves DSP-872, DSP-1096, DSP-778
=> DSP-872 Missing constants in js-lib

.github/workflows/main.yml
Try to re-init release-please. The recent release PR seems not to be updated automatically
=> chore: Try to re-activate release pr

.github/pull_request_template.md, .github/workflows/main.yml, README.md, package.json, scripts/typedoc-config.js, src/api/admin/lists/lists-endpoint-admin.ts, src/api/admin/lists/lists-endpoint.spec.ts, src/api/endpoint.spec.ts, src/api/endpoint.ts, src/api/v2/search/search-endpoint.spec.ts, src/index.ts, src/models/admin/update-child-node-request.ts, src/models/v2/Constants.ts, src/models/v2/custom-converters/base-url-converter.ts, test-framework/e2e/src/app.e2e-spec.ts, test-framework/src/app/app.component.html, test-framework/src/app/app.component.ts, test/data/api/admin/manually-generated/update-node-info-name-comment-label-request.json, test/data/api/admin/manually-generated/update-node-info-name-comment-label-response.json
Rebased 8 latest commit to fix commit messages, actually twice. 
resolves DSP-1189
=> chore: update PR title guideline and templates (DSP-1189)

src/api/v2/project-metadata/metadata-endpoint-v2.ts, src/models/v2/custom-converters/place-converter.ts, src/models/v2/project-metadata/metadata-conversion-util.ts, test-framework/src/app/app.component.ts
=> fix: metadata endpoint after DSP-API v.13.0.0 release (DSP-1232)

src/index.ts
=> feat(file value): export base file value classes (DSP-1262)

src/api/v2/ontology/ontologies-endpoint-v2.ts, src/api/v2/ontology/ontologies-endpoint.spec.ts, src/models/v2/ontologies/OntologyConversionUtil.ts, src/models/v2/ontologies/standoff-class-definition.ts, src/models/v2/ontologies/system-property-definition.ts, test-framework/e2e/src/app.e2e-spec.ts, test-framework/src/app/app.component.html, test-framework/src/app/app.component.ts, test/data/api/v2/manually-generated/minimal-ontology-with-all-languages-expanded.json, test/data/api/v2/manually-generated/minimal-ontology-with-all-languages.json
=> feat(ontology endpoint): get ontology in all langs (dsp-1230)

src/api/admin/lists/lists-endpoint-admin.ts, src/api/admin/lists/lists-endpoint.spec.ts
=> fix(lists-endpoint): getListNodeInfo return types (DSP-1278)

src/models/v2/custom-converters/union-element-array-of-elements-converter.ts, src/models/v2/custom-converters/union-orgnization-id-converter.ts, src/models/v2/custom-converters/union-person-organization-id-converter.ts, src/models/v2/custom-converters/union-string-array-of-strings-converter.ts, src/models/v2/custom-converters/union-url-string-converter.ts, src/models/v2/custom-converters/url-to-url-object-converter.ts, src/models/v2/project-metadata/attribution.ts, src/models/v2/project-metadata/dataset.ts, src/models/v2/project-metadata/grant.ts, src/models/v2/project-metadata/organization.ts, src/models/v2/project-metadata/person.ts, src/models/v2/project-metadata/single-project.ts, src/models/v2/project-metadata/update-project-metadata.ts, test-framework/src/app/app.component.html, test-framework/src/app/app.component.ts
=> feat(metadata-endpoint): expose all x-n properties as arrays (DSP-1306)

src/api/v2/project-metadata/metadata-endpoint-v2.ts, src/index.ts, src/models/v2/custom-converters/base-url-converter.ts, src/models/v2/custom-converters/distribution-converter.ts, src/models/v2/custom-converters/place-converter.ts, src/models/v2/custom-converters/union-advanced-url-object-converter.ts, src/models/v2/custom-converters/union-data-management-plan-id-converter.ts, src/models/v2/custom-converters/union-element-array-of-elements-converter.ts, src/models/v2/custom-converters/union-metadata-converter.ts, src/models/v2/custom-converters/union-orgnization-id-converter.ts, src/models/v2/custom-converters/union-person-organization-id-converter.ts, src/models/v2/custom-converters/union-single-project-id-converter.ts, src/models/v2/custom-converters/union-url-string-converter.ts, src/models/v2/custom-converters/url-to-url-object-converter.ts, src/models/v2/project-metadata/attribution.ts, src/models/v2/project-metadata/data-management-plan.ts, src/models/v2/project-metadata/dataset.ts, src/models/v2/project-metadata/grant.ts, src/models/v2/project-metadata/metadata-conversion-util.ts, src/models/v2/project-metadata/metadata-interfaces.ts, src/models/v2/project-metadata/organization.ts, src/models/v2/project-metadata/person.ts, src/models/v2/project-metadata/place.ts, src/models/v2/project-metadata/project-metadata.ts, src/models/v2/project-metadata/single-project.ts, test-framework/src/app/app.component.ts
=> feat(metadata-endpoint): test/implement flat response option (DSP-1223)

src/models/v2/custom-converters/union-data-management-plan-id-converter.ts, src/models/v2/custom-converters/union-element-array-of-elements-converter.ts, src/models/v2/custom-converters/union-orgnization-id-converter.ts, src/models/v2/custom-converters/union-person-organization-id-converter.ts, src/models/v2/custom-converters/union-single-project-id-converter.ts, src/models/v2/project-metadata/attribution.ts, test-framework/src/app/app.component.ts
=> fix(metadata-endpoint): ID conversion (DSP-1348)

src/api/admin/lists/lists-endpoint.spec.ts, src/models/admin/create-child-node-request.ts, test-framework/e2e/src/app.e2e-spec.ts, test-framework/src/app/app.component.html, test-framework/src/app/app.component.ts
=> refactor(create-child-node-request): add optional position property (DSP-1300)

.github/workflows/main.yml
resolves DSP-1379
For updates in github actions, the type is normally `chore`. But to test the changes I made, I decided to use the type `refactor` to see if it will take effect in release-please after merging this branch.
=> refactor(gh-ci): update release please configuration (DSP-1379)

src/api/admin/lists/lists-endpoint-admin.ts, src/api/admin/lists/lists-endpoint.spec.ts, src/index.ts, src/models/admin/list-child-node-response.ts, src/models/admin/list-child-node.ts
=> feat(lists-endpoint): Support for receiving a list child node from DSP-API (DSP-1385)

src/models/v2/project-metadata/data-management-plan.ts, src/models/v2/project-metadata/dataset.ts, src/models/v2/project-metadata/grant.ts, src/models/v2/project-metadata/organization.ts, src/models/v2/project-metadata/person.ts, src/models/v2/project-metadata/single-project.ts, test-framework/src/app/app.component.ts
=> fix(metadata-endpoint): types inconsistency (DSP-1388)

package-lock.json, package.json
resolves DSP-1606 and DSP-1607
It resolves most of the vulnerability issues mentioned here: <https://github.com/dasch-swiss/dsp-js-lib/security/dependabot>
=> chore(deps): update dependencies to fix vulnerability issue (DSP-1606 / DSP-1607)

.github/workflows/main.yml
=> chore(gihub actions): replace token

scripts/v2-test-data-config.json, src/api/v2/ontology/ontologies-endpoint-v2.ts, src/api/v2/ontology/ontologies-endpoint.spec.ts, src/index.ts, src/models/v2/Constants.ts, src/models/v2/ontologies/read/can-do-response.ts, test-framework/e2e/src/app.e2e-spec.ts, test-framework/src/app/app.component.html, test-framework/src/app/app.component.ts, test/data/api/v2/ontologies/can-do-response.json
=> feat(ontologies endpoint): check if entity can be deleted (DSP-1673)

src/api/v2/ontology/ontologies-endpoint-v2.ts, src/index.ts, src/models/v2/ontologies/update/update-resource-property-gui-element.ts, src/models/v2/ontologies/update/update-resource-property-label.ts, test-framework/e2e/src/app.e2e-spec.ts, test-framework/package-lock.json, test-framework/src/app/app.component.html, test-framework/src/app/app.component.ts
=> feat(ontology): new method to update gui element and attributes (DSP-1768)

src/index.ts, src/models/v2/Constants.ts, src/models/v2/resources/values/create/create-file-value.ts, src/models/v2/resources/values/read/read-file-value.ts, src/models/v2/resources/values/update/update-file-value.ts
=> feat(file-value): support all file value types (DSP-1777)

src/models/v2/resources/ResourcesConversionUtil.ts
resolves DSP-1795
Adds the missing conversion for file values like document, audio and moving image. I wanted to add some tests, but we do not have proper test-data for those cases.
=> chore(models): expand resource conversion (DSP-1795)

src/models/v2/resources/values/read/read-file-value.ts
=> fix(resource): optional file values (DSP-1803)

scripts/v2-test-data-config.json, src/api/v2/resource/resources-endpoint-v2.ts, src/api/v2/resource/resources-endpoint.spec.ts, test/data/api/v2/ontologies/can-do-response-expanded.json, test/data/api/v2/resources/erase-resource-request-expanded.json, test/data/api/v2/resources/erase-resource-request.json, test/data/api/v2/resources/erase-resource-response-expanded.json, test/data/api/v2/resources/erase-resource-response.json
=> feat(resource): add erase resource method (DSP-1807)

.github/workflows/codeql-analysis.yml
Suggested by Github; it's the same as we already have in dsp-app
=> chore(gh-ci): add code ql analysis to github actions

src/cache/ListAdminCache.spec.ts, src/cache/ListAdminCache.ts, src/cache/ListNodeV2Cache.spec.ts, src/cache/ListNodeV2Cache.ts, src/cache/UserCache.spec.ts, src/cache/UserCache.ts, src/cache/ontology-cache/OntologyCache.spec.ts, src/cache/ontology-cache/OntologyCache.ts, test-framework/src/app/app.component.html, test-framework/src/app/app.component.ts
=> feat(cache): reload cache methods (DSP-1913)

package-lock.json, src/models/v2/Constants.ts
To avoid a construct like this in DSP-App `subProp === Constants.KnoraApiV2 + Constants.HashDelimiter + 'isPartOf'`, I've updated the constants in DSP-JS.
=> feat(constants): add missing constants

.github/workflows/main.yml
Similar workflow as in DSP-APP. Not matrix environment needed
=> chore(gh): update gh-actions workflow

package-lock.json, package.json, test-framework/package-lock.json, test-framework/package.json
incl. upgrade to angular v13 in test-environment
=> chore(deps): fix security vulnerabilities

src/models/v2/resources/ResourcesConversionUtil.ts
=> fix: identify TextValueAsHtml as such even if it contains XML

scripts/mock-exports.json, src/api/system/health/health-conversion-util.ts, src/api/system/health/health-endpoint-system.ts, src/api/system/health/health-endpoint.spec.ts, src/api/system/version/version-endpoint-system.ts, src/models/system/health-response.ts, test/data/api/system/mock-health.ts
=> refactor(system)!: remove version from health request (DEV-651)

src/api/endpoint.ts
=> refactor: remove query retries in case of failure (DEV-670)

src/models/v2/resources/values/read/read-file-value.ts
=> refactor(value): optional dimension in moving image file value (DEV-676)

src/models/v2/Constants.ts
=> feat(knora-base): add missing constants (DEV-799)

src/index.ts, src/models/v2/resources/values/read/read-file-value.ts
=> feat(read-file-value): add ReadTextFileValue class (DEV-962)

src/api/admin/lists/lists-endpoint.spec.ts, src/models/v2/resources/values/read/read-file-value.ts
=> refactor(read-file-value): make the properties for a ReadDocumentFileValue optional (DEV-1304)

src/api/admin/groups/groups-endpoint.spec.ts, src/api/admin/lists/lists-endpoint.spec.ts, src/api/admin/permissions/permissions-endpoint.spec.ts, src/api/admin/projects/projects-endpoint-admin.ts, src/api/admin/projects/projects-endpoint.spec.ts, src/api/admin/users/users-endpoint.spec.ts, src/api/endpoint.ts, src/api/system/health/health-endpoint.spec.ts, src/api/v2/list/lists-endpoint.spec.ts, src/api/v2/ontology/ontologies-endpoint.spec.ts, src/api/v2/resource/resources-endpoint.spec.ts, src/api/v2/search/search-endpoint.spec.ts, src/api/v2/values/values-endpoint.spec.ts, src/cache/ListNodeV2Cache.spec.ts, src/cache/ontology-cache/OntologyCache.spec.ts, src/knora-api-config.spec.ts, src/knora-api-config.ts, src/models/v2/resources/ResourcesConversionUtil.spec.ts, test-framework/e2e/src/app.e2e-spec.ts, test-framework/src/app/app.component.html, test-framework/src/app/app.component.ts
=> feat!(zio-http): additional zio http support (DEV-1705)

src/api/admin/groups/groups-endpoint.spec.ts, src/api/admin/lists/lists-endpoint.spec.ts, src/api/admin/permissions/permissions-endpoint.spec.ts, src/api/admin/projects/projects-endpoint-admin.ts, src/api/admin/projects/projects-endpoint.spec.ts, src/api/admin/users/users-endpoint.spec.ts, src/api/endpoint.ts, src/api/system/health/health-endpoint.spec.ts, src/api/v2/list/lists-endpoint.spec.ts, src/api/v2/ontology/ontologies-endpoint.spec.ts, src/api/v2/resource/resources-endpoint.spec.ts, src/api/v2/search/search-endpoint.spec.ts, src/api/v2/values/values-endpoint.spec.ts, src/cache/ListNodeV2Cache.spec.ts, src/cache/ontology-cache/OntologyCache.spec.ts, src/knora-api-config.spec.ts, src/knora-api-config.ts, src/models/v2/resources/ResourcesConversionUtil.spec.ts, test-framework/src/app/app.component.html, test-framework/src/app/app.component.ts
Reverts dasch-swiss/dsp-js-lib#495
=> Revert "feat!(zio-http): additional zio http support (DEV-1705)"

src/api/admin/groups/groups-endpoint.spec.ts, src/api/admin/lists/lists-endpoint.spec.ts, src/api/admin/permissions/permissions-endpoint.spec.ts, src/api/admin/projects/projects-endpoint-admin.ts, src/api/admin/projects/projects-endpoint.spec.ts, src/api/admin/users/users-endpoint.spec.ts, src/api/endpoint.ts, src/api/system/health/health-endpoint.spec.ts, src/api/v2/list/lists-endpoint.spec.ts, src/api/v2/ontology/ontologies-endpoint.spec.ts, src/api/v2/resource/resources-endpoint.spec.ts, src/api/v2/search/search-endpoint.spec.ts, src/api/v2/values/values-endpoint.spec.ts, src/cache/ListNodeV2Cache.spec.ts, src/cache/ontology-cache/OntologyCache.spec.ts, src/knora-api-config.spec.ts, src/knora-api-config.ts, src/models/v2/resources/ResourcesConversionUtil.spec.ts, test-framework/e2e/src/app.e2e-spec.ts, test-framework/src/app/app.component.html, test-framework/src/app/app.component.ts
resolves DEV-1705
initial attempt was #495 but I messed up the title so release please didn't trigger
reverted merge in #496
=> feat(zio-http)!: additional zio http support (DEV-1705)

src/api/v2/search/search-endpoint-v2.ts, test-framework/e2e/src/app.e2e-spec.ts, test-framework/src/app/app.component.html, test-framework/src/app/app.component.ts
=> feat(search-endpoint): add method for search by label count

.github/workflows/main.yml
=> feat: publish release also to github packages

.github/workflows/main.yml
=> fix: main.yml

.github/workflows/main.yml
=> chore: downgrade release-please-action to v2

src/models/v2/Constants.ts
=> feat: updated constants (DEV-3477)

package.json, src/index.ts, src/models/v2/resources/values/update/update-file-value.ts
=> feat: implement editing of third party iiif images (DEV-3967)

package.json
=> chore: increase version for npm

.github/workflows/main.yml, src/cache/ListAdminCache.spec.ts
=> chore: update actions/checkout to v3 in CI

package.json, src/api/admin/groups/groups-endpoint-admin.ts, src/api/admin/lists/lists-endpoint-admin.ts, src/api/admin/lists/lists-endpoint.spec.ts, src/api/admin/permissions/permissions-endpoint-admin.ts, src/api/admin/projects/projects-endpoint-admin.ts, src/api/admin/users/users-endpoint-admin.ts, src/api/admin/users/users-endpoint.spec.ts, src/api/endpoint.ts, src/api/system/health/health-endpoint-system.ts, src/api/system/version/version-endpoint-system.ts, src/api/v2/authentication/authentication-endpoint-v2.ts, src/api/v2/list/lists-endpoint-v2.ts, src/api/v2/ontology/ontologies-endpoint-v2.ts, src/api/v2/resource/resources-endpoint-v2.ts, src/api/v2/search/search-endpoint-v2.ts, src/api/v2/values/values-endpoint-v2.ts, src/cache/ListAdminCache.spec.ts, src/cache/ListAdminCache.ts, src/cache/ListNodeV2Cache.ts, src/cache/UserCache.spec.ts, src/cache/UserCache.ts, src/cache/ontology-cache/OntologyCache.ts
=> feat: endpoints values do not return ApiResponseError type 

.github/workflows/main.yml
=> chore: use release please v4

.github/workflows/main.yml
=> fix: release please CI issue

.github/workflows/main.yml, README.md
=> fix: testing the release please workflow

.github/workflows/main.yml
=> chore: update release please type to node

README.md
=> fix: update readme and test github workflow

src/models/v2/resources/values/read/read-file-value.ts
=> fix: adjust license properties

src/api/v2/search/search-endpoint-v2.ts, src/api/v2/search/search-endpoint.spec.ts
=> feat: add endpoint for searching the incoming regions (DEV-4824)

src/models/v2/resources/values/read/read-file-value.ts
=> fix: revert license class optional fields

src/api/v2/search/search-endpoint-v2.ts, src/api/v2/search/search-endpoint.spec.ts
=> feat: add StillImageRepresentations endpoints (DEV-4836)

.claude/settings.json, CLAUDE.md
=> chore: initialize Claude Code
